name: bicycling
favicon: null
layout_spectrum: 0.4347550601232797
typography_spectrum: 0.6873175313230604
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.44322021724656224
  lightness: 0.2074671182781458
  saturation: 0.5986225609667599
  rhythmicContrast: 0.13157501351088285
purpose: []
